# These are supported funding model platforms

github: kuafuRace
patreon: # Replace with a single Patreon username
open_collective: carbon
ko_fi: carbon
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: carbon
liberapay: kuafuRace
issuehunt: kuafuRace
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://www.gouguoyin.com/zanzhu.html']
