name: test

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

jobs:

  test:
    strategy:
        matrix:
          vm-os: [ ubuntu-latest, macos-latest ]
          go-version: [1.14, 1.15, 1.16]
    runs-on: ${{ matrix.vm-os }}
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
    steps:
    - name: Install go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      uses: actions/checkout@v3

    - name: Test and create coverage file
      run: go test -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage file to codecov
      uses: codecov/codecov-action@v3
      with:
          token: ${{secrets.CODECOV_TOKEN}}
